
# 决斗系列插件 设置
duel_cfg: 
  # 随机依赖系数和战斗力依赖系数，不需要战斗力把Magnification2改成0就可以了
  Magnification: 1
  Magnification2: 1
  # 命令间隔时间，单位秒，这是决斗的冷却时间#初始为300秒
  Cooakashag_time: 300
  # 命令间隔时间，单位分钟，这是修炼的冷却时间#初始为300分钟
  Cooakashag_time2: 300
  # 命令间隔时间，单位分钟，这是突破的冷却时间#初始为30分钟
  Cooakashag_time3: 30