# 这个里面的东西，使用者可以自由修改，但是后果自负。使用“#刷新akasha配置”重置配置
# 点赞 设置
thumbUp_cfg: 
  # 是否全局点赞(还需要你点赞名单为空)和是否回复提醒,1是，2否
  everyone: 1 
  reply_something: 2
  # 最短点赞时间间隔，单位秒；回复概率
  time: 60
  huifu: 30

# 青云客 设置:初始概率和，每次改变量
ai_cfg: 
  gailv: 0.5
  gailv_: 0.1
  ai_api: http://api.qingyunke.com/api.php?key=free&appid=0&msg=

# 决斗系列插件 设置
duel_cfg: 
  # 随机依赖系数和战斗力依赖系数，不需要战斗力把Magnification2改成0就可以了
  Magnification: 1
  Magnification2: 1
  # 命令间隔时间，单位秒，这是决斗的冷却时间#初始为300秒
  Cooakashag_time: 300
  # 命令间隔时间，单位分钟，这是修炼的冷却时间#初始为300分钟
  Cooakashag_time2: 300
  # 命令间隔时间，单位分钟，这是突破的冷却时间#初始为30分钟
  Cooakashag_time3: 30